import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ColorSchemeScript } from "@mantine/core";
import Head from "next/head";
import Providers from "./layout/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <ColorSchemeScript />
      </Head>

      <body className={inter.className}>
        {/* Next Auth Google Provider */}
        <script
          defer
          src="https://www.gstatic.com/firebasejs/8.0/firebase.js"
        ></script>
        <script defer src="/static/google-provider.js"></script>

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
