#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Testing before commiting'

# check TypeScript
npm run check:types ||
(
    echo 'Failed type check'
    false;
)

# check Prettier
npm run check:format ||
(
    echo 'Failed Prettier check, pls format code using "npm run format"'
    false;
)

# check ESLint
npm run lint ||
(
    echo 'Failed ESLint check'
    false;
)

# TODO: Fix this, for some reason it's throwing an error
# try to build
# echo 'Trying to build'
# npx next build ||
# (
#     echo 'Build failed'
#     false;
# )

echo 'All test passed'
echo 'Commiting to repository'